sudo apt update && sudo apt-get install -y fail2ban
sudo systemctl status fail2ban

/etc/fail2ban/jail.local
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
banaction = iptables-multiport

[sshd]
enabled = true
port = ssh
logpath = /var/log/auth.log
maxretry = 3
findtime = 600
bantime = 3600
backend = systemd

sudo systemctl restart fail2ban
sudo systemctl enable fail2ban
