---

- name: Iнсталювати Docker i Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Запустити i увiмкнути Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Створення репозиторiю для зберiгання файлiв i логiв
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - /home/ubuntu/app
    - /var/log

- name: Копiювання ключа SSH з пайплайну
  copy:
    src: /home/runner/.ssh/ssh_private_key
    dest: /home/ubuntu/.ssh/ssh_private_key
    mode: '0600'

- name: Копiювання GitHub репозиторiю з вихiдним кодом
  git:
    repo: "git@github.com:KastonI/final-project-src.git"
    dest: "/home/ubuntu/app"
    version: master
    key_file: "/home/ubuntu/.ssh/ssh_private_key"
    force: yes
    accept_hostkey: yes
    depth: 1

- name: Деплой config.json з пiдстановкоб rtsp потокiв
  template:
    src: templates/config.json.j2
    dest: /home/ubuntu/app/config.json
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  vars:
    RTSP_URL_1: "{{ lookup('env', 'RTSP_URL_1') }}"
    RTSP_URL_2: "{{ lookup('env', 'RTSP_URL_2') }}"


- name: Запис змiнних у файл
  lineinfile:
    create: yes
    path: /etc/environment
    line: '{{ item.key }}="{{ lookup("env", item.value) }}"'
  loop:
    - { key: "TZ", value: "TZ" }
    - { key: "S3_BUCKET_NAME", value: "S3_BUCKET_NAME" }
    - { key: "NUM_CAMERAS", value: "NUM_CAMERAS" }
    - { key: "MAX_BUFFER_SIZE", value: "MAX_BUFFER_SIZE" }
    - { key: "RECORD_DURATION", value: "RECORD_DURATION" }
    - { key: "AWS_REGION", value: "AWS_REGION" }

- name: Зупинити Docker Compose файл якщо створений
  shell: |
    docker-compose down --rmi all --volumes --remove-orphans
  args:
    chdir: /home/ubuntu/app

- name: Деплой Docker Compose файлу
  shell: |
    docker-compose up --build -d
  args:
    chdir: /home/ubuntu/app