- name: Install nginx
  apt:
    name:
      - nginx
    state: present
    update_cache: yes

- name: Find private Ip for instance role_rtsp
  set_fact:
    rtsp_private_ip: "{{ hostvars[groups['role_rtsp'][0]]['private_ip_address'] }}"
  when: groups['role_rtsp'] | length > 0 and 'private_ip_address' in hostvars[groups['role_rtsp'][0]]

- name: Print private ip for rtsp instance
  debug:
    msg: "Private ip for rtsp: {{ private_ip_address }}"

- name: Cpoy nginx.conf with private ip
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: '0644'
  notify:
    - Restart Nginx
  when: rtsp_private_ip is defined