- name: Iнсталювати Docker i Docker Compose
  apt:
    name:
      - nginx
    state: present
    update_cache: yes

- name:
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: '0644'
  notify:
    - Restart Nginx