plugin: amazon.aws.aws_ec2
regions:
  - "{{ lookup('env', 'AWS_REGION') }}"
filters:
  instance-state-name: running
keyed_groups:
  - key: ec2_tags.role
    prefix: role
host_key_checks: false
hostnames:
  - tag:role
compose:
  ansible_host: "{{ public_ip_address if ec2_tags.role == 'bastion' else private_ip_address }}"
