# - name: Configure baseline
#   hosts: all
#   become: true
#   roles:
#     - baseline

- name: Configure Nginx instance
  hosts: role_nginx
  become: true
  roles:
    - nginx


- name: Configure rtsp instance
  hosts: role_rtsp
  become: true
  roles:
    - docker
