---

- hosts: role_bastion
  gather_facts: yes
  become: yes
  roles:
    - role: bastion

- hosts: role_nginx
  gather_facts: yes
  become: yes
  roles:
    - role: nginx

- hosts: role_rtsp
  gather_facts: yes
  become: yes
  roles:
    - role: rtsp