name: Terraform-deploy
on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'  # Запускаем только если менялись файлы в terraform/
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_s3_records: ${{ vars.S3_RECORDS }}
      TF_VAR_availability_zone: ${{ vars.AVAILABILITY_ZONE }}
      TF_VAR_aws_instance: ${{ vars.AWS_INSTANCE }}
      TF_VAR_instance_type: ${{ vars.INSTANCE_TYPE }}
      TF_VAR_key_name: ${{ vars.KEY_NAME }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      - name: Terraform Init
        working-directory: ./terraform        
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
