name: Terraform-deploy
on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'  # Run only when there was a push in terraform/
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_s3_records: ${{ vars.S3_BUCKET_NAME }}
      TF_VAR_availability_zone: ${{ vars.AVAILABILITY_ZONE }}
      TF_VAR_aws_instance: ${{ vars.AWS_INSTANCE }}
      TF_VAR_instance_type: ${{ vars.INSTANCE_TYPE }}
      TF_VAR_instance_type_rtsp: ${{ vars.INSTANCE_TYPE_RTSP }}
      TF_VAR_ssh_public_key: ${{ vars.SSH_PUBLIC_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      - name: Terraform Init
        working-directory: ./terraform        
        run: | 
          terraform init \
            -backend-config="bucket=${{ vars.S3_TFSTATE_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -compact-warnings
